

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.01:3306/inhatc?serverTimezone=UTC&characterEncoding=UTF-8
    username: inhatc
    password: inhatc

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    user:
      name: 201844050@itc.ac.kr
      password: 123456


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8080